# render.yaml
services:
  - type: web
    name: portfolio-site
    runtime: python
    buildCommand: ""
    startCommand: gunicorn portfolio_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_site.settings
      - key: PYTHON_VERSION
        value: 3.10
